### PR TITLE
Updating documentation to cut out testrpc as a dependency

### PR DESCRIPTION
**Pull request by pimotte**
Small fixes

### CODE REVIEW

**Comment by pimotte** [comment]
Testing yields weird issues in the interaction between MetaMask and the truffle develop testrpc (possibly due to re-using the seed), so not merging this for now.

**Comment by pimotte** [comment]
MetaMask is making efforts to resolve this: https://github.com/MetaMask/metamask-extension/issues/1999 When the resulting code has been merged, we can move away from stand-alone testrpc, hopefully.

**Comment by nikita-fuchs** [comment]
C'mon guys, the documentation needs to be updated ;) Is there still something wrong with this PR ?

**Comment by pimotte** [comment]
Well, the issue I linked to to MetaMask in the last comment is still open, so my guess is that developing using `truffle develop` still requires periodic reinstallation of MetaMask, which, in my opinion, is not acceptable. 

I would probably prefer switching to ganache as the recommended test-blockchain, as that is what the truffle team seems to be pushing. If I find time to test that and update the docs I will, but I'm a little short on time at the moment, so unless a PR for that magically appears *hint hint* it will stay this way for now :stuck_out_tongue:

**Comment by pimotte** [comment]
So I actually got to doing it xD Fixed with #39

**Pull request closed without merging**
