### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by PJUllrich**
Updated the readme for how to log in with a testing account of `testrpc` in MetaMask

### CODE REVIEW

**Comment by pimotte** [comment]
Thanks for the PR!

While this is one of the ways to couple MetaMask, I would generally advise to use the 12-word mnemonic phrase that is printed on startup. (and can be provided with the -m option on testrpc). 
The way you've written it down, you'll need import each account one key at a time. Also described here: http://truffleframework.com/docs/advanced/truffle-with-metamask

Given the confusion, I do think this step warrants more explanation and/or the inclusion to the link above,  but I rather not recommend importing the private keys.

**Comment by PJUllrich** [comment]
Uh yeah that's a better way to do it indeed! I'll update the readme accordingly.

**Comment by pimotte** [comment]
Awesome. I'll wait for that then. I'm currently writing about the pre-reqs that I didn't realize existed. (Something about node.js, as well as the necessity of Python and git).

**Comment by PJUllrich** [comment]
I updated the Readme to contain a link to the official Truffle documentation you gave me.

**Comment by pimotte** [comment]
Merged:) I made some extra changes and moved it into it's own section. Feel free to let me know if you have more feedback/ideas to make this clearer.

**Pull request merged**
